name: "PR Checks"
on: [pull_request, push]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: "npm ci"
      run: npm ci

    - name: "npm run build"
      run: npm run build

    - name: "npm run test"
      run: npm run test

    - name: "check for unformatted sources"
      run: |
        npm run format:check \
        || (echo "##[error] found unformatted files. please 'npm run format'" \
                 "and check in all changes" \
            && exit 1)
    - name: "check for uncommitted changes"
      run: |
        git diff --exit-code --stat -- . ':!node_modules' \
        || (echo "##[error] found changed files after build. please 'npm run build'" \
                 "and check in all changes" \
            && exit 1)